CREATE DATABASE IF NOT EXISTS lawfirm
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE lawfirm;

CREATE TABLE IF NOT EXISTS migrations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
