<input type="hidden" name="_token" value="<?= htmlspecialchars(AppCoreCsrf::token(), ENT_QUOTES, 'UTF-8') ?>">
<label class="admin-field admin-field--wide"><span>Title</span><input name="title" required value="<?= htmlspecialchars((string) $slide['title'], ENT_QUOTES, 'UTF-8') ?>"></label>
<label class="admin-field admin-field--wide"><span>Description</span><textarea name="body" rows="5"><?= htmlspecialchars((string) $slide['body'], ENT_QUOTES, 'UTF-8') ?></textarea></label>
<label class="admin-field"><span>Desktop image</span><select name="media_id"><option value="">No image selected</option><?php foreach ($mediaOptions as $media): ?><option value="<?= (int) $media['id'] ?>" <?= (string) $slide['media_id'] === (string) $media['id'] ? 'selected' : '' ?>>#<?= (int) $media['id'] ?> — <?= htmlspecialchars($media['filename'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label>
<label class="admin-field"><span>Mobile image</span><select name="mobile_media_id"><option value="">Use desktop image</option><?php foreach ($mediaOptions as $media): ?><option value="<?= (int) $media['id'] ?>" <?= (string) $slide['mobile_media_id'] === (string) $media['id'] ? 'selected' : '' ?>>#<?= (int) $media['id'] ?> — <?= htmlspecialchars($media['filename'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label>
<label class="admin-field"><span>Primary button</span><input name="primary_label" value="<?= htmlspecialchars((string) $slide['primary_label'], ENT_QUOTES, 'UTF-8') ?>"></label>
<label class="admin-field"><span>Primary URL</span><input name="primary_url" value="<?= htmlspecialchars((string) $slide['primary_url'], ENT_QUOTES, 'UTF-8') ?>"></label>
<label class="admin-field"><span>Secondary button</span><input name="secondary_label" value="<?= htmlspecialchars((string) $slide['secondary_label'], ENT_QUOTES, 'UTF-8') ?>"></label>
<label class="admin-field"><span>Secondary URL</span><input name="secondary_url" value="<?= htmlspecialchars((string) $slide['secondary_url'], ENT_QUOTES, 'UTF-8') ?>"></label>
<label class="admin-field"><span>Overlay opacity (0–1)</span><input type="number" name="overlay_opacity" min="0" max="1" step="0.01" value="<?= htmlspecialchars((string) $slide['overlay_opacity'], ENT_QUOTES, 'UTF-8') ?>"></label>
<label class="admin-field"><span>Display order</span><input type="number" name="sort_order" min="0" value="<?= (int) $slide['sort_order'] ?>"></label>
<label class="admin-check"><input type="checkbox" name="is_enabled" value="1" <?= (int) $slide['is_enabled'] === 1 ? 'checked' : '' ?>> <span>Show this slide</span></label>